module.exports.Token = require('./token.model')
module.exports.User = require('./user.model')
module.exports.Movie = require('./movie.model')
module.exports.Comment = require('./comment.model')
module.exports.Point = require('./point.model')
