module.exports.authService = require('./auth.service')
module.exports.emailService = require('./email.service')
module.exports.tokenService = require('./token.service')
module.exports.userService = require('./user.service')
module.exports.movieService = require('./movie.service')
module.exports.commentService = require('./comment.service')
module.exports.pointService = require('./point.service')
